version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get info
          command: |
            docker info
      - run:
          name: Build the custom container
          command: |
            docker build -t $DOCKER_USER/rrtools.test  .
          no_output_timeout: 4h
      - run:
          name: Test if the container can be started
          command: |
            docker run --name rrtools.test -d -p 8787:8787 $DOCKER_USER/rrtools.test
